// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-inject/gulp-inject.d.ts
declare module "gulp-inject" {

    import File = require("vinyl");

    interface ITagFunction {
        (targetExt: string, sourceExt: string): string;
    }

    interface ITransformFunction {
        (filepath: string, file?: File, index?: number, length?: number, targetFile?: File): string;
    }

    interface IOptions {
        ignorePath?: string | string[];
        relative?: boolean;
        addPrefix?: string;
        addSuffix?: string;
        addRootSlash?: boolean;
        name?: string;
        removeTags?: boolean;
        empty?: boolean;
        starttag?: string | ITagFunction;
        endtag?: string | ITagFunction;
        transform?: ITransformFunction;
        selfClosingTag?: boolean;
    }

    function inject(sources: NodeJS.ReadableStream, options?: IOptions): NodeJS.ReadWriteStream;

    namespace inject {}

    export = inject;
}
