// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/jsesc/jsesc.d.ts
declare module 'jsesc' {

	function jsesc(str: string, opts?: any): string;

	namespace jsesc {
		var version: string;

		interface Opts {
			quotes?: string;
			wrap?: boolean;
			es6?: boolean;
			escapeEverything?: boolean;
			compact?: boolean;
			indent?: string;
			json?: boolean;
		}
	}

	export = jsesc;
}
