/*
Deployment script for Expenses

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO

USE [master];


GO

PRINT N'Creating Expenses...'
GO
CREATE DATABASE [Expenses.End] COLLATE SQL_Latin1_General_CP1_CI_AS
GO

USE [Expenses.End];


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/



GO

GO
PRINT N'Creating [Catalog]...';


GO
CREATE SCHEMA [Catalog]
    AUTHORIZATION [dbo];


GO
PRINT N'Creating [Expense]...';


GO
CREATE SCHEMA [Expense]
    AUTHORIZATION [dbo];


GO
PRINT N'Creating [Expenses]...';


GO
CREATE SCHEMA [Expenses]
    AUTHORIZATION [dbo];


GO
PRINT N'Creating [Purchase]...';


GO
CREATE SCHEMA [Purchase]
    AUTHORIZATION [dbo];


GO
 CREATE SCHEMA [Audit] 
 AUTHORIZATION [dbo];



GO
PRINT N'Creating [Catalog].[Product]...';


GO
CREATE TABLE [Catalog].[Product] (
    [Id]                INT             IDENTITY (1, 1) NOT NULL,
    [Title]             NVARCHAR (50)   NOT NULL,
    [Description]       NVARCHAR (500)  NOT NULL,
    [Price]             FLOAT (53)      NOT NULL,
    [CreationDate]      DATETIME2 (7)   NOT NULL,
    [Available]         BIT             NOT NULL,
    [ProductCategoryId] SMALLINT        NOT NULL,
    [LargePicture]      VARBINARY (MAX) NULL,
    [ThumbnailPicture]  VARBINARY (MAX) NULL,
    CONSTRAINT [PK_Catalog.Products] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Catalog].[Product].[IX_ProductCategoryId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ProductCategoryId]
    ON [Catalog].[Product]([ProductCategoryId] ASC);


GO
PRINT N'Creating [Catalog].[ProductCategory]...';


GO
CREATE TABLE [Catalog].[ProductCategory] (
    [Id]    SMALLINT      IDENTITY (1, 1) NOT NULL,
    [Title] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_Catalog.ProductCategories] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Expense].[SuspiciousExpense]...';


GO
CREATE TABLE [Expense].[SuspiciousExpense] (
    [Id]                  INT IDENTITY (1, 1) NOT NULL,
    [SuspiciousExpenseId] INT NOT NULL,
    CONSTRAINT [PK_SuspiciousExpense] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Expense].[ExpenseBonus]...';


GO
CREATE TABLE [Expense].[ExpenseBonus] (
    [Id]        INT            IDENTITY (1, 1) NOT NULL,
    [Amount]    FLOAT (53)     NOT NULL,
    [Reason]    NVARCHAR (250) NOT NULL,
    [ExpenseId] INT            NOT NULL,
    CONSTRAINT [PK_Expenses.ExpenseBonus] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Expense].[ExpenseBonus].[IX_ExpenseId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ExpenseId]
    ON [Expense].[ExpenseBonus]([ExpenseId] ASC);


GO
PRINT N'Creating [Expense].[Bonification]...';


GO
CREATE TABLE [Expense].[Bonification] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [Amount]            FLOAT (53)     NOT NULL,
    [Enabled]           BIT            NOT NULL,
    [Description]       NVARCHAR (200) NOT NULL,
    [From]              DATETIME2 (7)  NOT NULL,
    [To]                DATETIME2 (7)  NOT NULL,
    [EmployeeId]        INT            NOT NULL,
    [ExpenseCategoryId] SMALLINT       NOT NULL,
    CONSTRAINT [PK_Expenses.Bonifications] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Expense].[Bonification].[IX_EmployeeId]...';


GO
CREATE NONCLUSTERED INDEX [IX_EmployeeId]
    ON [Expense].[Bonification]([EmployeeId] ASC);


GO
PRINT N'Creating [Expense].[Bonification].[IX_ExpenseCategoryId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ExpenseCategoryId]
    ON [Expense].[Bonification]([ExpenseCategoryId] ASC);


GO
PRINT N'Creating [Expense].[CostCenter]...';


GO
CREATE TABLE [Expense].[CostCenter] (
    [Id]          SMALLINT       IDENTITY (1, 1) NOT NULL,
    [Code]        NVARCHAR (50)  NOT NULL,
    [Description] NVARCHAR (200) NULL,
    CONSTRAINT [PK_Expenses.CostCenters] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Expense].[Expense]...';


GO
CREATE TABLE [Expense].[Expense] (
    [Id]                INT             IDENTITY (1, 1) NOT NULL,
    [EnabledFrom]       DATETIME2 (7)   NULL,
    [EnabledTo]         DATETIME2 (7)   NULL,
    [Title]             NVARCHAR (50)   NOT NULL,
    [Notes]             NVARCHAR (250)  NULL,
    [Amount]            FLOAT (53)      NOT NULL,
    [ExpenseReportId]   INT             NOT NULL,
    [ExpenseCategoryId] SMALLINT        NOT NULL,
    [ReceiptPicture]    VARBINARY (MAX) NULL,
    [Date]              DATETIME2 (7)   NOT NULL,
    CONSTRAINT [PK_Expenses.Expenses] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Expense].[Expense].[IX_ExpenseReportId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ExpenseReportId]
    ON [Expense].[Expense]([ExpenseReportId] ASC);


GO
PRINT N'Creating [Expense].[Expense].[IX_ExpenseCategoryId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ExpenseCategoryId]
    ON [Expense].[Expense]([ExpenseCategoryId] ASC);


GO
PRINT N'Creating [Expense].[ExpenseCategory]...';


GO
CREATE TABLE [Expense].[ExpenseCategory] (
    [Id]            SMALLINT       IDENTITY (1, 1) NOT NULL,
    [Title]         NVARCHAR (50)  NOT NULL,
    [Description]   NVARCHAR (250) NOT NULL,
    [DefaultAmount] FLOAT (53)     NOT NULL,
    CONSTRAINT [PK_Expenses.ExpenseCategories] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Expense].[ExpenseReport]...';


GO
CREATE TABLE [Expense].[ExpenseReport] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [CostCenterId]      SMALLINT       NOT NULL,
    [Purpose]           NVARCHAR (250) NOT NULL,
    [CreatedOn]         DATETIME2 (7)  NOT NULL,
    [EmployeeId]        INT            NOT NULL,
    [Status]            SMALLINT       NOT NULL,
    [Description]       NVARCHAR (255) NULL,
    [SequenceNumber]    AS             ((('ER' + CONVERT (NVARCHAR (MAX), [EmployeeId])) + '-') + CONVERT (NVARCHAR (MAX), [Id])),
    [Summary]           NVARCHAR (250) NULL,
    [SubmissionDate]    DATETIME2 (7)  NULL,
    [ReimburseInPoints] BIT            NOT NULL,
    [VersionTimeStamp]  ROWVERSION     NOT NULL,
    CONSTRAINT [PK_Expenses.ExpenseReports] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Expense].[ExpenseReport].[IX_CostCenterId]...';


GO
CREATE NONCLUSTERED INDEX [IX_CostCenterId]
    ON [Expense].[ExpenseReport]([CostCenterId] ASC);


GO
PRINT N'Creating [Expense].[ExpenseReport].[IX_EmployeeId]...';


GO
CREATE NONCLUSTERED INDEX [IX_EmployeeId]
    ON [Expense].[ExpenseReport]([EmployeeId] ASC);


GO
PRINT N'Creating [Expense].[Picture]...';


GO
CREATE TABLE [Expense].[Picture] (
    [Id]          INT             IDENTITY (1, 1) NOT NULL,
    [PictureType] SMALLINT        NOT NULL,
    [EmployeeId]  INT             NOT NULL,
    [Content]     VARBINARY (MAX) NOT NULL,
    CONSTRAINT [PK_Expenses.Pictures] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Expense].[Picture].[IX_EmployeeId]...';


GO
CREATE NONCLUSTERED INDEX [IX_EmployeeId]
    ON [Expense].[Picture]([EmployeeId] ASC);


GO
PRINT N'Creating [Expense].[PredictionModel]...';


GO
CREATE TABLE [Expense].[PredictionModel] (
    [model] VARBINARY (MAX) NULL
);


GO
PRINT N'Creating [Expense].[Team]...';


GO
CREATE TABLE [Expense].[Team] (
    [Id]       INT            IDENTITY (1, 1) NOT NULL,
    [TeamName] NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_Expenses.Teams] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Expense].[Employee]...';


GO
CREATE TABLE [Expense].[Employee] (
    [Id]                INT           IDENTITY (1, 1) NOT NULL,
    [FirstName]         NVARCHAR (50) NOT NULL,
    [LastName]          NVARCHAR (50) NOT NULL,
    [Email]             NVARCHAR (60) NOT NULL,
    [Identifier]        NVARCHAR (50) NOT NULL,
    [JobTitle]          NVARCHAR (50) NOT NULL,
    [TeamId]            INT           NOT NULL,
    [IsTeamManager]     BIT           NOT NULL,
    [BankAccountNumber] NVARCHAR (17) NOT NULL,
    CONSTRAINT [PK_Expenses.Employees] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Expense].[Employee].[IX_TeamId]...';


GO
CREATE NONCLUSTERED INDEX [IX_TeamId]
    ON [Expense].[Employee]([TeamId] ASC);


GO

CREATE TABLE [Expense].[PermissionMap] (
    [Id]            INT           IDENTITY (1, 1) NOT NULL,
    [EmployeeId]    INT           NOT NULL,
    [Email]         VARBINARY (128) NOT NULL,
    [TeamId]        INT           NOT NULL,
    [IsTeamManager] BIT           NOT NULL,
    CONSTRAINT [PermissionMap_PK] PRIMARY KEY NONCLUSTERED ([Id] ASC)
);

PRINT N'Creating [Purchase].[EmployeePurchase]...';


GO
CREATE TABLE [Purchase].[EmployeePurchase] (
    [EmployeeId]      INT      NOT NULL,
    [BuyerCategoryId] SMALLINT NOT NULL,
    [Points]          FLOAT      NULL,
    CONSTRAINT [PK_Purchase.[EmployeePurchase] PRIMARY KEY CLUSTERED ([EmployeeId] ASC)
);


GO
PRINT N'Creating [Purchase].[AccountMovement]...';


GO
CREATE TABLE [Purchase].[AccountMovement] (
    [Id]           INT            IDENTITY (1, 1) NOT NULL,
    [Movement]     FLOAT (53)     NOT NULL,
    [MovementDate] DATETIME2 (7)  NOT NULL,
    [Notes]        NVARCHAR (500) NULL,
    [EmployeeId]   INT            NOT NULL,
    CONSTRAINT [PK_Purchase.AccountMovements] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Purchase].[AccountMovement].[IX_AccountId]...';


GO
CREATE NONCLUSTERED INDEX [IX_AccountId]
    ON [Purchase].[AccountMovement]([EmployeeId] ASC);


GO
PRINT N'Creating [Purchase].[BuyerCategory]...';


GO
CREATE TABLE [Purchase].[BuyerCategory] (
    [Id]                    SMALLINT      IDENTITY (1, 1) NOT NULL,
    [Name]                  NVARCHAR (50) NOT NULL,
    [MaxPointsInFiscalYear] FLOAT (53)    NOT NULL,
    CONSTRAINT [PK_Purchase.BuyerCategories] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Purchase].[PurchaseOrder]...';


GO
CREATE TABLE [Purchase].[PurchaseOrder] (
    [Id]         INT IDENTITY (1, 1) NOT NULL,
    [EmployeeId] INT NOT NULL,
    CONSTRAINT [PK_Purchase.PurchaseOrders] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Purchase].[PurchaseOrder].[IX_BuyerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_BuyerId]
    ON [Purchase].[PurchaseOrder]([EmployeeId] ASC);


GO
PRINT N'Creating [Purchase].[PurchaseOrderItem]...';


GO
CREATE TABLE [Purchase].[PurchaseOrderItem] (
    [Id]                INT           IDENTITY (1, 1) NOT NULL,
    [PurchaseHistoryId] INT           NOT NULL,
    [ProductId]         INT           NOT NULL,
    [ProductName]       NVARCHAR (50) NOT NULL,
    [Price]             FLOAT (53)    NOT NULL,
    [ItemsNumber]       INT           NOT NULL,
    [PurchaseDate]      DATETIME2 (7) NOT NULL,
    CONSTRAINT [PK_Purchase.PurchaseOrderItems] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Purchase].[PurchaseOrderItem].[IX_PurchaseHistoryId]...';


GO
CREATE NONCLUSTERED INDEX [IX_PurchaseHistoryId]
    ON [Purchase].[PurchaseOrderItem]([PurchaseHistoryId] ASC);


GO
PRINT N'Creating unnamed constraint on [Expense].[Expense]...';


GO
ALTER TABLE [Expense].[Expense]
    ADD DEFAULT ('1900-01-01T00:00:00.000') FOR [Date];


GO
PRINT N'Creating unnamed constraint on [Expense].[ExpenseReport]...';


GO
ALTER TABLE [Expense].[ExpenseReport]
    ADD DEFAULT ((0)) FOR [ReimburseInPoints];


GO
PRINT N'Creating unnamed constraint on [Purchase].[EmployeePurchase]...';


GO
ALTER TABLE [Purchase].[EmployeePurchase]
    ADD DEFAULT ((0)) FOR [BuyerCategoryId];


GO
PRINT N'Creating unnamed constraint on [Purchase].[BuyerCategory]...';


GO
ALTER TABLE [Purchase].[BuyerCategory]
    ADD DEFAULT ((0)) FOR [MaxPointsInFiscalYear];


GO
PRINT N'Creating [Catalog].[FK_Catalog.Products_Catalog.ProductCategories_ProductCategoryId]...';


GO
ALTER TABLE [Catalog].[Product]
    ADD CONSTRAINT [FK_Catalog.Products_Catalog.ProductCategories_ProductCategoryId] FOREIGN KEY ([ProductCategoryId]) REFERENCES [Catalog].[ProductCategory] ([Id]);


GO
PRINT N'Creating [Expense].[FK_SuspiciousExpense_Expense]...';


GO
ALTER TABLE [Expense].[SuspiciousExpense]
    ADD CONSTRAINT [FK_SuspiciousExpense_Expense] FOREIGN KEY ([SuspiciousExpenseId]) REFERENCES [Expense].[Expense] ([Id]);


GO
PRINT N'Creating [Expense].[FK_Expenses.ExpenseBonus_Expenses.Expenses_ExpenseId]...';


GO
ALTER TABLE [Expense].[ExpenseBonus]
    ADD CONSTRAINT [FK_Expenses.ExpenseBonus_Expenses.Expenses_ExpenseId] FOREIGN KEY ([ExpenseId]) REFERENCES [Expense].[Expense] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [Expense].[FK_Expense.Bonifications_Expense.Employees_EmployeeId]...';


GO
ALTER TABLE [Expense].[Bonification]
    ADD CONSTRAINT [FK_Expense.Bonifications_Expense.Employees_EmployeeId] FOREIGN KEY ([EmployeeId]) REFERENCES [Expense].[Employee] ([Id]);


GO
PRINT N'Creating [Expense].[FK_Expenses.Bonifications_Expenses.Employees_EmployeeId]...';


GO
ALTER TABLE [Expense].[Bonification]
    ADD CONSTRAINT [FK_Expenses.Bonifications_Expenses.Employees_EmployeeId] FOREIGN KEY ([EmployeeId]) REFERENCES [Expense].[Employee] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [Expense].[FK_Expenses.Bonifications_Expenses.ExpenseCategories_ExpenseCategoryId]...';


GO
ALTER TABLE [Expense].[Bonification]
    ADD CONSTRAINT [FK_Expenses.Bonifications_Expenses.ExpenseCategories_ExpenseCategoryId] FOREIGN KEY ([ExpenseCategoryId]) REFERENCES [Expense].[ExpenseCategory] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [Expense].[FK_Expenses.Expenses_Expenses.ExpenseCategories_ExpenseCategoryId]...';


GO
ALTER TABLE [Expense].[Expense]
    ADD CONSTRAINT [FK_Expenses.Expenses_Expenses.ExpenseCategories_ExpenseCategoryId] FOREIGN KEY ([ExpenseCategoryId]) REFERENCES [Expense].[ExpenseCategory] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [Expense].[FK_Expenses.Expenses_Expenses.ExpenseReports_ExpenseReportId]...';


GO
ALTER TABLE [Expense].[Expense]
    ADD CONSTRAINT [FK_Expenses.Expenses_Expenses.ExpenseReports_ExpenseReportId] FOREIGN KEY ([ExpenseReportId]) REFERENCES [Expense].[ExpenseReport] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [Expense].[FK_Expenses.ExpenseReports_Expenses.CostCenters_CostCenterId]...';


GO
ALTER TABLE [Expense].[ExpenseReport]
    ADD CONSTRAINT [FK_Expenses.ExpenseReports_Expenses.CostCenters_CostCenterId] FOREIGN KEY ([CostCenterId]) REFERENCES [Expense].[CostCenter] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [Expense].[FK_Expenses.ExpenseReports_Expenses.Employees_EmployeeId]...';


GO
ALTER TABLE [Expense].[ExpenseReport]
    ADD CONSTRAINT [FK_Expenses.ExpenseReports_Expenses.Employees_EmployeeId] FOREIGN KEY ([EmployeeId]) REFERENCES [Expense].[Employee] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [Expense].[FK_Expenses.Pictures_Expenses.Employees_EmployeeId]...';


GO
ALTER TABLE [Expense].[Picture]
    ADD CONSTRAINT [FK_Expenses.Pictures_Expenses.Employees_EmployeeId] FOREIGN KEY ([EmployeeId]) REFERENCES [Expense].[Employee] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [Expense].[FK_Expenses.Employees_Expenses.Teams_TeamId]...';


GO
ALTER TABLE [Expense].[Employee]
    ADD CONSTRAINT [FK_Expenses.Employees_Expenses.Teams_TeamId] FOREIGN KEY ([TeamId]) REFERENCES [Expense].[Team] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [Purchase].[FK_Purchase.Buyers_Purchase.BuyerCategories_BuyerCategoryId]...';


GO
ALTER TABLE [Purchase].[EmployeePurchase]
    ADD CONSTRAINT [FK_Purchase.Buyers_Purchase.BuyerCategories_BuyerCategoryId] FOREIGN KEY ([BuyerCategoryId]) REFERENCES [Purchase].[BuyerCategory] ([Id]);


GO
PRINT N'Creating [Purchase].[FK_Purchase.EmployeePurchase_Expense_Employees_Id]...';


GO
ALTER TABLE [Purchase].[EmployeePurchase]
    ADD CONSTRAINT [FK_Purchase.EmployeePurchase_Expense_Employees_Id] FOREIGN KEY ([EmployeeId]) REFERENCES [Expense].[Employee] ([Id]);


GO
PRINT N'Creating [Purchase].[FK_Purchase.AccountMovements_Purchase.EmployeePurchase_EmployeeId]...';


GO
ALTER TABLE [Purchase].[AccountMovement]
    ADD CONSTRAINT [FK_Purchase.AccountMovements_Purchase.EmployeePurchase_EmployeeId] FOREIGN KEY ([EmployeeId]) REFERENCES [Purchase].[EmployeePurchase] ([EmployeeId]);


GO
PRINT N'Creating [Purchase].[FK_Purchase.PurchaseOrders_Purchase.EmployeePurchase_EmployeeId]...';


GO
ALTER TABLE [Purchase].[PurchaseOrder]
    ADD CONSTRAINT [FK_Purchase.PurchaseOrders_Purchase.EmployeePurchase_EmployeeId] FOREIGN KEY ([EmployeeId]) REFERENCES [Purchase].[EmployeePurchase] ([EmployeeId]);


GO
PRINT N'Creating [Purchase].[FK_Purchase.PurchaseOrderItems_Catalog.Product_ProductId]...';


GO
ALTER TABLE [Purchase].[PurchaseOrderItem]
    ADD CONSTRAINT [FK_Purchase.PurchaseOrderItems_Catalog.Product_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [Catalog].[Product] ([Id]);


GO
PRINT N'Creating [Purchase].[FK_Purchase.PurchaseOrderItems_Purchase.PurchaseOrders_PurchaseHistoryId]...';


GO
ALTER TABLE [Purchase].[PurchaseOrderItem]
    ADD CONSTRAINT [FK_Purchase.PurchaseOrderItems_Purchase.PurchaseOrders_PurchaseHistoryId] FOREIGN KEY ([PurchaseHistoryId]) REFERENCES [Purchase].[PurchaseOrder] ([Id]) ON DELETE CASCADE;


GO

PRINT N'Creating [Expense].[TrainSuspiciousExpensesModel]...';


GO

CREATE PROCEDURE [Expense].[TrainSuspiciousExpensesModel]
AS
BEGIN

TRUNCATE TABLE [Expense].[PredictionModel]

INSERT INTO [Expense].[PredictionModel]
exec sp_execute_external_script  @language =N'R',    
@script=N'
model.tree <- rpart (IsSuspicious~.,data=InputDataSet,method="class")	
trainedmodel<-data.frame(payload = as.raw(serialize(model.tree,connection=NULL)))
OutputDataSet<-trainedmodel',      
@input_data_1 =N'SELECT Amount, ExpenseCategoryId,
CASE
	WHEN se.SuspiciousExpenseId is not null
	THEN 1
	ELSE 0
	END as IsSuspicious
FROM [Expense].[Expense] e
LEFT JOIN Expense.SuspiciousExpense se
on e.Id = se.SuspiciousExpenseId'

END
GO

GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'Expenses', 'ON';
    END


GO






CREATE TABLE [Audit].[WebAudit](
	[Id] [int] IDENTITY(1,1) PRIMARY KEY NONCLUSTERED NOT NULL,
	[Email] [NVARCHAR](60) NOT NULL,
	[Path] [nvarchar](255) NULL,
	[RequestContent] [nvarchar](max) NULL,
	[Verb] [varchar](10) NULL,
	[ResponseCode] [nvarchar](3) NULL,
	[ResponseContent] [nvarchar](max) NULL,
	[Date] datetime2(7) NOT NULL)


GO

CREATE PROCEDURE [Audit].usp_Audit 
	@Email [nvarchar](60),
	@Path [nvarchar](255), 
	@RequestContent [nvarchar](max),
	@Verb [varchar](10),
	@ResponseCode [nvarchar](3),
	@ResponseContent [nvarchar](max)  
 AS   
	  INSERT INTO [Audit].[WebAudit]([Email], [Path], [RequestContent], [Verb], [ResponseCode], [ResponseContent], [Date])
	  VALUES (@Email, @Path, @RequestContent, @Verb, @ResponseCode, @ResponseContent, GETDATE())  
 GO  

 
PRINT N'Update complete.';


GO