// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-less/gulp-less.d.ts
declare module "gulp-less" {

    interface IOptions {
        modifyVars?: {};
        paths?: string[];
        plugins?: any[];
        relativeUrls?: boolean;
    }

    function less(options?: IOptions): NodeJS.ReadWriteStream;

    namespace less {}

    export = less;
}
