DROP DATABASE IF EXISTS [ExpensesDWH]
GO

CREATE DATABASE [ExpensesDWH]
GO

ALTER DATABASE [ExpensesDWH] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ExpensesDWH] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ExpensesDWH] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ExpensesDWH] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ExpensesDWH] SET ARITHABORT OFF 
GO
ALTER DATABASE [ExpensesDWH] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ExpensesDWH] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ExpensesDWH] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ExpensesDWH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ExpensesDWH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ExpensesDWH] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ExpensesDWH] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ExpensesDWH] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ExpensesDWH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ExpensesDWH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ExpensesDWH] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ExpensesDWH] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ExpensesDWH] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ExpensesDWH] SET MULTI_USER 
GO
ALTER DATABASE [ExpensesDWH] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ExpensesDWH] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ExpensesDWH] SET QUERY_STORE = OFF
GO
ALTER DATABASE [ExpensesDWH] SET  READ_WRITE 
GO