// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/inherits/inherits.d.ts
declare module "inherits" {
	import {inherits} from "util";
	export = inherits;
}
