// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-autoprefixer/gulp-autoprefixer.d.ts
declare module "gulp-autoprefixer" {
    namespace autoPrefixer {
        interface Options {
            browsers?: string[];
            cascade?: boolean;
            remove?: boolean;
        }
    }

    function autoPrefixer(opts?: autoPrefixer.Options): NodeJS.ReadWriteStream;

    export = autoPrefixer;
}
