module.exports = {
    NOTIFICATION_HUB: process.env.NOTIFICATION_HUB || 'XXXXXXXXXXX',
    NOTIFICATION_SECRET: process.env.NOTIFICATION_SECRET || 'Endpoint=sb://XXXXXXXXXXX-namespace.servicebus.windows.net/;SharedAccessKeyName=DefaultFullSharedAccessSignature;SharedAccessKey=XXXXXXXXXXX',
    DOCUMENT_DB_ENDPOINT: process.env.DOC_DB_ENDPOINT || 'XXXXXXXXXX',
    DOCUMENT_DB_PRIMARYKEY: process.env.DOC_DB_PRIMARYKEY || 'XXXXXXXXXX',
    DOCUMENT_DB_DATABASE: process.env.DOC_DB_DATABASE || 'XXXXXXXXXX',
    DOCUMENT_DB_SEAT: process.env.DOC_DB_SEAT || 'XXXXXXXXXX',
    DOCUMENT_DB_BOOKING: process.env.DOC_DB_BOOKING || 'XXXXXXXXXX',
    DOCUMENT_DB_Flight: process.env.DOC_DB_Flight || 'XXXXXXXXXX',
    GET_SOLOSERVICE: process.env.GET_SOLOSERVICE || 'XXXXXXXXXX',
    GRAPH_DB_ENDPOINT: process.env.GRAPH_DB_ENDPOINT || 'XXXXXXXXXX',
    GRAPH_DB_PRIMARYKEY: process.env.GRAPH_DB_PRIMARYKEY || 'XXXXXXXXXX',
    GRAPH_DB_DATABASE: process.env.GRAPH_DB_DATABASE || 'XXXXXXXXXX',
    GRAPH_DB_COLLECTION: process.env.GRAPH_DB_COLLECTION || 'XXXXXXXXXX'
};
