module.exports = {
    DOCUMENT_DB_ENDPOINT: process.env.DOCUMENT_DB_ENDPOINT || 'XXXXXXXXXX',
    DOCUMENT_DB_PRIMARYKEY: process.env.DOCUMENT_DB_PRIMARYKEY || 'XXXXXXXXXX',
    DOCUMENT_DB_DATABASE: process.env.DOCUMENT_DB_DATABASE || 'BotDB',
    DOCUMENT_DB_FLIGHT_COLLECTION: process.env.DOCUMENT_DB_FLIGHT_COLLECTION || 'Flights',
    DOCUMENT_DB_BOOKING_COLLECTION: process.env.DOCUMENT_DB_BOOKING_COLLECTION || 'Bookings',
    DOCUMENT_DB_ALTERNATIVE_FLIGHT_COLLECTION: process.env.DOCUMENT_DB_ALTERNATIVE_FLIGHT_COLLECTION || 'AlternativeFlights'
};

